const languages = {
	PG_SPONSOR: {
		en: 'Sponsored',
		vi: 'Được tài trợ',
		fr: 'Sponsorisé',
		fr_CA: 'Commandité',
		pt: 'Patrocinado',
		nl: 'Gesponsord',
		it: 'Sponsorizzato',
		ja: '広告',
		zh: '贊助'
	},
	PG_MENU_HIDE_AD: {
		en: 'Hide ad',
		vi: 'Ẩn quảng cáo',
		fr: 'Masquer la publicité',
		fr_CA: 'Masquer la publicité',
		pt: 'Ocultar anúncio',
		nl: 'Advertentie verbergen',
		it: 'Nascondi inserzione',
		ja: 'この広告を非表示にする',
		zh: '隱藏廣告'
	},
	PG_MENU_HIDE_AD_DESCRIPTION: {
		en: 'Never see this ad again',
		vi: 'Bạn sẽ không bao giờ nhìn thấy quảng cáo này nữa',
		fr: 'Ne plus jamais voir cette publicité',
		fr_CA: 'Ne plus jamais voir cette publicité',
		pt: 'Não volte a ver esse anúncio',
		nl: 'Deze advertentie niet meer weergeven',
		it: 'Non mostrare di nuovo questa inserzione',
		ja: 'この広告は表示されなくなります',
		zh: '不要再看到這則廣告'
	},
	PG_MENU_REPORT: {
		en: 'Report ad',
		vi: 'Báo cáo quảng cáo',
		fr: 'Signaler une publicité',
		fr_CA: 'Signaler une publicité',
		pt: 'Denunciar anúncio',
		nl: 'Advertentie rapporteren',
		it: 'Segnala inserzione',
		ja: ' 広告を報告',
		zh: '檢舉廣告'
	},
	PG_MENU_REPORT_DESCRIPTION: {
		en: 'Tell us about a problem with this ad',
		vi: 'Hãy cho chúng tôi biết quảng cáo này có vấn đề gì',
		fr: 'Signalez-nous tout problème avec cette pub',
		fr_CA: 'Signalez-nous tout problème avec cette pub',
		pt: 'Conte-nos sobre um problema com esse anúncio',
		nl: 'Vertel ons over een probleem met deze advertentie',
		it: 'Comunicaci se ci sono problemi con questa inserzione',
		ja: 'この広告に関する問題をお知らせください',
		zh: '告訴我們這則廣告有何問題'
	},
	PG_MENU_SAVE_AD: {
		en: 'Save post',
		vi: 'Lưu bài viết',
		fr: 'Sauvegarder la publication',
		fr_CA: 'Sauvegarder la publication',
		pt: 'Salvar link',
		nl: 'Bericht opslaan',
		it: 'Salva il post',
		ja: '投稿を保存',
		zh: '儲存影片'
	},
	PG_MENU_SAVE_AD_DESCRIPTION: {
		en: 'Add this to your saved items',
		vi: 'Thêm mục này vào mục đã lưu',
		fr: 'Ajouter à vos éléments enregistrés',
		fr_CA: 'Ajouter à vos éléments enregistrés',
		pt: 'Adicione esse item aos seus itens salvos',
		nl: 'Dit toevoegen aan opgeslagen items',
		it: 'Aggiungi agli elementi salvati',
		ja: '保存済みのアイテムにこのアイテムを追加',
		zh: '加入珍藏項目'
	},
	PG_MENU_UN_SAVE_AD: {
		en: 'Unsave post',
		vi: 'Bỏ lưu liên kết',
		fr: 'Annuler l’enregistrement de la publication',
		fr_CA: 'Annuler l’enregistrement de la publication',
		pt: 'Remover link dos Salvos',
		nl: 'Bericht verwijderen',
		it: 'Rimuovi il post dagli elementi salvati',
		ja: '投稿の保存を取り消し',
		zh: '取消儲存影片'
	},
	PG_MENU_UN_SAVE_AD_DESCRIPTION: {
		en: 'Remove this from your saved items',
		vi: 'Gỡ mục này khỏi mục đã lưu',
		fr: 'Supprimez ceci de vos éléments enregistrés',
		fr_CA: 'Retirer de vos éléments sauvegardés',
		pt: 'Remova isso de seus itens salvos',
		nl: 'Dit verwijderen uit je opgeslagen items',
		it: 'Rimuovi questo elemento da quelli salvati',
		ja: '保存済みのアイテムからこのアイテムを削除',
		zh: '從珍藏項目中移除'
	},
	PG_MENU_WYS_AD: {
		en: 'Why am I seeing this ad?',
		vi: 'Tại sao tôi nhìn thấy quảng cáo này',
		fr: 'Pourquoi vois-je cette publicité?',
		fr_CA: 'Pourquoi vois-je cette publicité?',
		pt: 'Por que estou vendo esse anúncio?',
		nl: 'Waarom krijg ik deze advertentie te zien?',
		it: 'Perché visualizzo questa inserzione?',
		ja: 'この広告が表示されている理由',
		zh: '為什麼我會看到這則廣告？'
	},
	PG_SAVE_SUCCESSFUL: {
		en: 'You have saved successfully.',
		vi: 'Bạn đã lưu thành công',
		fr: 'Vous avez enregistré avec succès',
		fr_CA: 'Vous avez enregistré avec succès',
		pt: 'Você salvou com sucesso',
		nl: 'U hebt met succes opgeslagen',
		it: 'Hai salvato con successo',
		ja: '正常に保存しました',
		zh: '為什麼我會看到這則廣告？'
	},
	PG_LIKE: {
		en: 'Like',
		vi: 'Thích',
		fr_CA: 'J’aime',
		fr: 'J’aime',
		pt: 'Curtir',
		nl: 'Leuk',
		it: 'Mi piace',
		ja: 'いいね！',
		zh: '讚'
	},
	PG_SHARE: {
		en: 'Share',
		vi: 'Chia sẻ',
		fr_CA: 'Partager',
		fr: 'Partager',
		pt: 'Compartilhar',
		nl: 'Delen',
		it: 'Condividi',
		ja: 'シェアする',
		zh: '分享'
	},
	PG_COMMENT: {
		en: 'Comment',
		vi: 'Bình luận',
		fr_CA: 'Commenter',
		fr: 'Commenter',
		pt: 'Comentar',
		nl: 'Opmerking',
		it: 'Commenta',
		ja: 'コメント',
		zh: '留言'
	},
	PG_SHARES: {
		en: 'shares',
		vi: 'lượt chia sẻ',
		fr_CA: 'partages',
		fr: 'partages',
		pt: 'compartilhamentos',
		nl: 'keer gedeeld',
		it: 'condivisioni',
		ja: 'シェア',
		zh: '次分享'
	},
	PG_COMMENTS: {
		en: 'comments',
		vi: 'bình luận',
		fr_CA: 'commentaires',
		fr: 'commentaires',
		pt: 'comentários',
		nl: 'opmerkingen',
		it: 'Commenti',
		ja: 'コメント',
		zh: '則留言'
	},
	PG_HIDE_TITLE: {
		en: 'All ads from Pexgle hidden',
		vi: 'Đã ẩn toàn bộ quảng cáo từ Pexgle',
		fr_CA: 'Publicité masquée',
		pt: 'Anúncio ocultado',
		nl: 'Advertentie is verborgen',
		it: 'Inserzione nascosta',
		ja: '広告が非表示になりました',
		zh: '隱藏此廣告商的所有廣告'
	},
	PG_HIDE_DESCRIPTION: {
		en: 'You won&#39;t see ads from Pexgle anymore',
		vi: 'Bạn sẽ không nhìn thấy quảng cáo từ Pexgle nữa.',
		fr: 'Vous ne verrez pas cette publicité dans votre fil d’actualité.',
		fr_CA: 'Vous ne verrez pas cette publicité dans votre fil d’actualité.',
		pt: 'Você não verá esse anúncio no seu Feed de Notícias.',
		nl: 'Je krijgt deze advertentie niet te zien in je nieuwsoverzicht',
		it: 'Non vedrai questa inserzione nella tua sezione Notizie.',
		ja: 'この広告はニュースフィードで表示されなくなります。',
		zh: '你將不會看到 Pexgle 的廣告。'
	},
	PG_UNDO: {
		en: 'Undo',
		vi: 'Hoàn tác',
		fr: 'Annuler',
		fr_CA: 'Annuler',
		pt: 'Desfazer',
		nl: 'Ongedaan maken',
		it: 'Annulla',
		ja: '元に戻す',
		zh: '取消'
	},
	PG_THANKS: {
		en: 'Thank you for your feedback!',
		vi: 'Cảm ơn ý kiến của bạn!',
		fr: 'Merci pour vos commentaires !',
		fr_CA: 'Merci pour vos commentaires !',
		pt: 'Agradecemos seu feedback!',
		nl: 'Bedankt voor je feedback.',
		it: 'Grazie per il tuo feedback!',
		ja: `ありがとうございました。`,
		zh: '感謝您的意見回饋！'
	},
	PG_HIDED_AD_POPUP: {
		en: 'Ad Hidden',
		vi: 'Đã ẩn quảng cáo',
		fr: 'Publicité masquée',
		fr_CA: 'Publicité masquée',
		pt: 'Anúncio ocultado',
		nl: 'Advertentie is verborgen',
		it: 'Inserzione nascosta',
		ja: '広告を非表示',
		zh: '已隱藏廣告'
	},
	PG_HIDED_AD: {
		en: 'Ad Hidden',
		vi: 'Đã ẩn quảng cáo',
		fr: 'Publicité masquée',
		fr_CA: 'Publicité masquée',
		pt: 'Anúncio ocultado',
		nl: 'Advertentie is verborgen',
		it: 'Inserzione nascosta',
		ja: '広告が非表示になりました',
		zh: '廣告已隱藏'
	},
	PG_HIDED_AD_DES: {
		en: 'You won&#39;t see this ad in your News Feed',
		vi: 'Bạn sẽ không nhìn thấy quảng cáo này trong Bảng tin của mình.',
		fr: 'Vous ne verrez pas cette publicité dans votre fil d’actualité.',
		fr_CA: 'Vous ne verrez pas cette publicité dans votre fil d’actualité',
		pt: 'Você não verá esse anúncio no seu Feed de Notícias.',
		nl: 'Je krijgt deze advertentie niet te zien in je nieuwsoverzicht',
		it: 'Non vedrai questa inserzione nella tua sezione Notizie.',
		ja: 'この広告はニュースフィードで表示されなくなります。',
		zh: '你不會在動態消息中看到這則廣告。'
	},
	PG_HIDED_AD_QUESTION: {
		en: 'Please tell us why you hid this ad.',
		vi: 'Vui lòng cho biết vì sao bạn ẩn quảng cáo này.',
		fr: 'Dites-nous pourquoi vous avez masqué cette pub.',
		fr_CA: 'Dites-nous pourquoi vous avez masqué cette pub.',
		pt: 'Diga-nos por que você ocultou esse anúncio.',
		nl: 'Vertel ons waarom je deze advertentie hebt verborgen.',
		it: 'Spiegaci perché hai nascosto questa inserzione.',
		ja: 'この広告を非表示にした理由をお聞かせください。',
		zh: '請告訴我們你為何隱藏此廣告。'
	},
	PG_HIDED_AD_REASON_1: {
		en: 'Already purchased',
		vi: 'Đã mua hàng rồi',
		fr: 'Déjà acheté',
		fr_CA: 'Déjà acheté',
		pt: 'Já comprado',
		nl: 'Al gekocht',
		it: 'Acquisto già effettuato',
		ja: '購入済み',
		zh: '已購買'
	},
	PG_HIDED_AD_REASON_2: {
		en: 'Too personal',
		vi: 'Quá riêng tư',
		fr: 'Trop personnel',
		fr_CA: 'Trop personnel',
		pt: 'Pessoal demais',
		nl: 'Te persoonlijk',
		it: 'Troppo personale',
		ja: '個人的すぎる',
		zh: '太私人'
	},
	PG_HIDED_AD_REASON_3: {
		en: 'Repetitive',
		vi: 'Xuất hiện quá nhiều lần',
		fr: 'Répétitif',
		fr_CA: 'Répétitif',
		pt: 'Repetitivo',
		nl: 'Herhalend',
		it: 'Ripetitiva',
		ja: '何度も表示される',
		zh: '重複'
	},
	PG_HIDED_AD_REASON_4: {
		en: 'Irrelevant',
		vi: 'Không phù hợp',
		fr: 'Hors de propos',
		fr_CA: 'Hors de propos',
		pt: 'Irrelevante',
		nl: 'Irrelevant',
		it: 'Non pertinente',
		ja: '関連性がない',
		zh: '不相關'
	},
	PG_HIDED_AD_REASON_5: {
		en: 'Knows too much',
		vi: 'Biết quá nhiều',
		fr: 'En sait trop',
		fr_CA: 'En sait trop',
		pt: 'Sabe demais',
		nl: 'Weet te veel',
		it: 'Conosce troppe informazioni',
		ja: '自分のことを知りすぎている',
		zh: '知道太多資訊'
	},
	PG_HIDED_AD_REASON_6: {
		en: 'Sensitive topic',
		vi: 'Chủ đề nhạy cảm',
		fr: 'Sujet sensible',
		fr_CA: 'Sujet sensible',
		pt: 'Tópico sensível',
		nl: 'Gevoelig onderwerp',
		it: 'Argomento delicato',
		ja: ' デリケートなトピック',
		zh: '敏感主題'
	},
	PG_HIDED_AD_FINISH: {
		en: 'Done',
		vi: 'Xong',
		fr: 'OK',
		fr_CA: 'Terminer',
		pt: 'Concluir',
		nl: 'Klaar',
		it: 'Fine',
		ja: '完了',
		zh: '完成'
	},
	PG_AD_REPORT: {
		en: 'Report This Ad',
		vi: 'Báo cáo quảng cáo này',
		fr: 'Signaler une publicité',
		fr_CA: 'Signaler cette publicité',
		pt: 'Denunciar esse anúncio',
		nl: 'Deze advertentie rapporteren',
		it: 'Segnala questa inserzione',
		ja: 'この広告を報告',
		zh: '檢舉此廣告'
	},
	PG_AD_REPORT_DESCRIPTION: {
		en: 'Help us understand what&#39;s happening with this ad. How would you describe it?',
		vi: 'Giúp chúng tôi hiểu rõ quảng cáo này đang gặp vấn đề gì. Bạn sẽ mô tả vấn đề đó như thế nào?',
		fr: 'Aidez-nous à comprendre le problème avec cette publicité. Comment la décririez-vous?',
		fr_CA: 'Aidez-nous à comprendre le problème avec cette publicité. Comment la décririez-vous?',
		pt: 'Ajude-nos a entender o que está acontecendo com esse anúncio. Como você o descreveria? ',
		nl: 'Vertel ons wat er met deze advertentie aan de hand is. Hoe zou jij het probleem beschrijven?',
		it: 'Aiutaci a comprendere cosa succede con questa inserzione. Come la descriveresti?',
		ja: 'この広告の問題点をお聞かせください。',
		zh: '協助我們瞭解這則廣告有什麼問題。你會如何描述這則廣告？'
	},
	PG_AD_REPORT_1: {
		en: 'Misleading or Scam',
		vi: 'Gây hiểu lầm hoặc lừa đảo',
		fr: 'Trompeur ou indésirable',
		fr_CA: 'Trompeur ou indésirable',
		pt: ' Enganoso ou fraudulento',
		nl: 'Misleidende inhoud of oplichting',
		it: 'Fuorviante o truffa',
		ja: '詐欺または誤解を招くコンテンツ',
		zh: '誤導或詐欺'
	},
	PG_AD_REPORT_2: {
		en: 'Sexually Inappropriate',
		vi: 'Thiếu đứng đắn về mặt tình dục',
		fr: 'C’est sexuellement inapproprié',
		fr_CA: 'C’est sexuellement inapproprié',
		pt: ' Sexualmente inadequado',
		nl: ' Seksueel ongepast',
		it: 'Contenuti sessuali inappropriati',
		ja: '性的に不適切',
		zh: '有不當的色情內容'
	},
	PG_AD_REPORT_3: {
		en: 'Offensive',
		vi: 'Xúc phạm',
		fr: 'Offensant',
		fr_CA: 'Offensant',
		pt: 'Ofensivo',
		nl: 'Aanstootgevend',
		it: 'Contenuti offensivi',
		ja: '不快な内容である',
		zh: '冒犯他人'
	},
	PG_AD_REPORT_4: {
		en: 'Violence',
		vi: 'Bạo lực',
		fr: 'Violence',
		fr_CA: 'Violence',
		pt: 'Violência',
		nl: 'Geweld',
		it: 'Violenza',
		ja: '暴力',
		zh: '暴力'
	},
	PG_AD_REPORT_5: {
		en: 'Prohibited Content',
		vi: 'Nội dung bị cấm',
		fr: 'Contenu interdit',
		fr_CA: 'Contenu interdit',
		pt: 'Conteúdo proibido',
		nl: 'Verboden inhoud',
		it: 'Contenuti vietati',
		ja: '禁止されているコンテンツ',
		zh: '違禁內容'
	},
	PG_AD_REPORT_6: {
		en: 'Spam',
		vi: 'Spam',
		fr: 'Spam',
		fr_CA: 'Spam',
		pt: 'Spam',
		nl: 'Spam',
		it: 'Spam',
		ja: 'スパム',
		zh: '垃圾訊息'
	},
	PG_AD_REPORT_7: {
		en: 'False News',
		vi: 'Tin giả',
		fr: 'Fausse information',
		fr_CA: 'Fausse information',
		pt: 'Notícia falsa',
		nl: 'Nepnieuws',
		it: 'Notizia falsa',
		ja: 'フェイクニュース',
		zh: '不實報導'
	},
	PG_AD_REPORT_8: {
		en: 'Other',
		vi: 'Khác',
		fr: 'Autre',
		fr_CA: 'Autre',
		pt: 'Outro',
		nl: 'Overig',
		it: 'Altro',
		ja: 'その他',
		zh: '其他'
	},
	PG_AD_REPORT_INFO: {
		en: `<span class="_67pz">Learn more about our <a href="https://www.facebook.com/policies/ads/" onClick ="closeHideReason();">Ad Policies</a>.</span>`,
		vi: `<span class="_67pz">Tìm hiểu thêm về <a href="https://www.facebook.com/policies/ads/" onClick ="closeHideReason();">Chính sách quảng cáo</a> của chúng tôi.</span>`,
		fr_CA: `<span class="_67pz">En savoir plus sur nos <a href="https://www.facebook.com/policies/ads/" onClick ="closeHideReason();">Règles publicitaires</a>.</span>`,
		fr: `<span class="_67pz">En savoir plus sur nos <a href="https://www.facebook.com/policies/ads/" onClick ="closeHideReason();">Règles publicitaires</a>.</span>`,
		pt: `<span class="_67pz">Saiba mais sobre nossas <a href="https://www.facebook.com/policies/ads/" onClick ="closeHideReason();">Políticas de Anúncios</a>.</span>`,
		nl: `<span class="_67pz">Meer informatie over ons <a href="https://www.facebook.com/policies/ads/" onClick ="closeHideReason();">advertentiebeleid</a>.</span>`,
		it: `<span class="_67pz">Scopri di più sulle nostre <a href="https://www.facebook.com/policies/ads/" onClick ="closeHideReason();">Normative pubblicitarie</a>.</span>`,
		ja: `<span class="_67pz"><a href="https://www.facebook.com/policies/ads/" onClick ="closeHideReason();">広告ポリシー</a>に関する詳しい情報をご確認ください。</span>`,
		zh: `<span class="_67pz">深入瞭解我們的<a href="https://www.facebook.com/policies/ads/">廣告刊登政策</a>。</span>`
	},
	PG_AD_REPORT_SEND: {
		en: 'Submit',
		vi: 'Gửi',
		fr: 'Envoyer',
		fr_CA: 'Envoyer',
		pt: 'Enviar',
		nl: 'Verzenden',
		it: 'Invia',
		ja: '送信する',
		zh: '提交'
	},
	PG_AD_REPORT_REPORTED: {
		en: 'Ad Reported',
		vi: 'Đã báo cáo quảng cáo',
		fr: 'Pub signalée.',
		fr_CA: 'Pub signalée.',
		pt: 'Anúncio denunciado',
		nl: 'Advertentie gerapporteerd.',
		it: 'Inserzione segnalata',
		ja: '広告を報告しました',
		zh: '已檢舉廣告'
	},
	PG_AD_REPORT_NOT_DISPLAY_AGAIN: {
		en: 'We won&#39;t show you this ad again.',
		vi: 'Không hiển thị lại nữa',
		fr: 'Nous ne vous montrerons plus cette pub.',
		fr_CA: 'Nous ne vous montrerons plus cette pub.',
		pt: 'Não mostraremos esse anúncio para você novamente.',
		nl: 'We laten je deze advertentie niet meer zien.',
		it: 'Non ti mostreremo più questa inserzione.',
		ja: 'この広告は今後表示されません。',
		zh: '我們不會再向你顯示這則廣告。'
	},
	PG_WYS_HEADER: {
		en: 'Why am I seeing this ad?',
		vi: 'Tại sao bạn nhìn thấy quảng cáo này',
		fr: 'Voici pourquoi vous voyez cette pub',
		fr_CA: 'Voici pourquoi vous voyez cette pub',
		pt: 'Por que você está vendo esse anúncio',
		nl: 'Waarom je deze advertentie ziet',
		it: 'Perché vedi questa inserzione',
		ja: 'この広告が表示される理由',
		zh: '你為何會看到這則廣告'
	},
	PG_WYS_ONLY_YOU: {
		en: 'Only you can see this',
		vi: 'Chỉ mình bạn xem được thông tin này',
		fr: 'Vous seul(e) pouvez voir cela',
		fr_CA: 'Vous seul(e) pouvez voir cela',
		pt: 'Somente você pode ver isso',
		nl: 'Alleen jij kunt dit zien',
		it: 'Visibile solo a te',
		ja: '他の人には表示されません',
		zh: '你為何會看到這則廣告'
	},
	PG_WYS_REASON_HEADER: {
		en: `<span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; overflow-wrap: normal; text-align: left; color: rgb(96, 103, 112);">You&#39;re seeing this ad because your information matches <a target="_blank" href="%PAGE_LINK%"><span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; font-weight: bold; overflow-wrap: normal; text-align: left; color: rgb(28, 30, 33);"><span class="dgpf1xc5 c77takrd ikxir1m9 it4nsc65 mnmr0lgl b6ewvobd pesago7c fpaaicyn" title="Pexgle">Pexgle&#39;s</span></span></a> advertising requests. There could also be more factors not listed here. <div class="dgpf1xc5" accessibilityrole="button"><a target="_blank" href="/help/794535777607370" style="text-decoration-color: var(--fds-black);"><span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; font-weight: bold; overflow-wrap: normal; text-align: left; color: rgb(28, 30, 33);">Learn More</span></a></div></span>`,
		vi: `<span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; overflow-wrap: normal; text-align: left; color: rgb(96, 103, 112);">Bạn nhìn thấy quảng cáo này vì thông tin của bạn khớp với yêu cầu của <a target="_blank" href="/%PAGE_LINK%"><span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; font-weight: bold; overflow-wrap: normal; text-align: left; color: rgb(28, 30, 33);"><span class="dgpf1xc5 c77takrd ikxir1m9 it4nsc65 mnmr0lgl b6ewvobd pesago7c fpaaicyn" title="Pexgle">Pexgle</span></span></a>. Ngoài ra, còn có các lý do khác. <div class="dgpf1xc5" accessibilityrole="button"><a target="_blank" href="/help/794535777607370" style="text-decoration-color: var(--fds-black);"><span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; font-weight: bold; overflow-wrap: normal; text-align: left; color: rgb(28, 30, 33);">Tìm hiểu thêm</span></a></div></span>`,
		fr_CA: `<span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; overflow-wrap: normal; text-align: left; color: rgb(96, 103, 112);">Vous voyez cette pub car vos informations correspondent aux requêtes publicitaires <a target="_blank" href="%PAGE_LINK%"><span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; font-weight: bold; overflow-wrap: normal; text-align: left; color: rgb(28, 30, 33);"><span class="dgpf1xc5 c77takrd ikxir1m9 it4nsc65 mnmr0lgl b6ewvobd pesago7c fpaaicyn" title="Yeah1 TV">de Yeah1 TV</span></span></a>. Il se peut que d’autres facteurs, qui ne sont pas référencés ici, entrent en jeu. <div class="dgpf1xc5" accessibilityrole="button"><a target="_blank" href="/help/794535777607370" style="text-decoration-color: var(--fds-black);"><span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; font-weight: bold; overflow-wrap: normal; text-align: left; color: rgb(28, 30, 33);">En savoir plus</span></a></div></span>`,
		fr: `<span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; overflow-wrap: normal; text-align: left; color: rgb(96, 103, 112);">Vous voyez cette pub car vos informations correspondent aux requêtes publicitaires <a target="_blank" href="%PAGE_LINK%"><span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; font-weight: bold; overflow-wrap: normal; text-align: left; color: rgb(28, 30, 33);"><span class="dgpf1xc5 c77takrd ikxir1m9 it4nsc65 mnmr0lgl b6ewvobd pesago7c fpaaicyn" title="Pexgle">de Pexgle</span></span></a>. Il se peut que d’autres facteurs, qui ne sont pas référencés ici, entrent en jeu. <div class="dgpf1xc5" accessibilityrole="button"><a target="_blank" href="/help/794535777607370" style="text-decoration-color: var(--fds-black);"><span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; font-weight: bold; overflow-wrap: normal; text-align: left; color: rgb(28, 30, 33);">En savoir plus</span></a></div></span>`,
		pt: `<span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; overflow-wrap: normal; text-align: left; color: rgb(96, 103, 112);">Você está vendo esse anúncio porque suas informações correspondem às solicitações de publicidade <a target="_blank" href="%PAGE_LINK%"><span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; font-weight: bold; overflow-wrap: normal; text-align: left; color: rgb(28, 30, 33);"><span class="dgpf1xc5 c77takrd ikxir1m9 it4nsc65 mnmr0lgl b6ewvobd pesago7c fpaaicyn" title="Công ty Mắt Bão">de Công ty Mắt Bão</span></span></a>. Pode haver também outros fatores que não aparecem listados aqui. <div class="dgpf1xc5" accessibilityrole="button"><a target="_blank" href="/help/794535777607370" style="text-decoration-color: var(--fds-black);"><span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; font-weight: bold; overflow-wrap: normal; text-align: left; color: rgb(28, 30, 33);">Saiba mais</span></a></div></span>`,
		nl: `<span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; overflow-wrap: normal; text-align: left; color: rgb(96, 103, 112);">Je ziet deze advertentie omdat je informatie overeenkomt met de advertentieverzoeken van <a target="_blank" href="%PAGE_LINK%"><span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; font-weight: bold; overflow-wrap: normal; text-align: left; color: rgb(28, 30, 33);"><span class="dgpf1xc5 c77takrd ikxir1m9 it4nsc65 mnmr0lgl b6ewvobd pesago7c fpaaicyn" title="Pexgle">Pexgle</span></span></a>. Er is mogelijk sprake van meer factoren die hier niet worden vermeld. <div class="dgpf1xc5" accessibilityrole="button"><a target="_blank" href="/help/794535777607370" style="text-decoration-color: var(--fds-black);"><span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; font-weight: bold; overflow-wrap: normal; text-align: left; color: rgb(28, 30, 33);">Meer informatie</span></a></div></span>`,
		it: `<span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; overflow-wrap: normal; text-align: left; color: rgb(96, 103, 112);">Vedi questa inserzione perché le tue informazioni corrispondono alle richieste pubblicitarie di <a target="_blank" href="%PAGE_LINK%"><span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; font-weight: bold; overflow-wrap: normal; text-align: left; color: rgb(28, 30, 33);"><span class="dgpf1xc5 c77takrd ikxir1m9 it4nsc65 mnmr0lgl b6ewvobd pesago7c fpaaicyn" title="Pexgle">di Pexgle</span></span></a>. Potrebbero esserci anche altri fattori non indicati qui. <div class="dgpf1xc5" accessibilityrole="button"><a target="_blank" href="/help/794535777607370" style="text-decoration-color: var(--fds-black);"><span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; font-weight: bold; overflow-wrap: normal; text-align: left; color: rgb(28, 30, 33);">Scopri di più</span></a></div></span>`,
		ja: `<span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; overflow-wrap: normal; text-align: left; color: rgb(96, 103, 112);">この広告が表示される理由の1つに、あなたの情報が<a target="_blank" href="%PAGE_LINK%"><span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; font-weight: bold; overflow-wrap: normal; text-align: left; color: rgb(28, 30, 33);"><span class="dgpf1xc5 c77takrd ikxir1m9 it4nsc65 mnmr0lgl b6ewvobd pesago7c fpaaicyn" title="Pexgle">Pexgle</span></span></a>広告リクエストにマッチしている点が挙げられます。また、ここに表示されない要素が他にもある可能性があります。<div class="dgpf1xc5" accessibilityrole="button"><a target="_blank" href="/help/794535777607370" style="text-decoration-color: var(--fds-black);"><span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; font-weight: bold; overflow-wrap: normal; text-align: left; color: rgb(28, 30, 33);">詳しくはこちら</span></a></div></span>`,
		zh: `<span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; overflow-wrap: normal; text-align: left; color: rgb(96, 103, 112);">你會看到這則廣告，是因為你的資料符合<a target="_blank" href="%PAGE_LINK%"><span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; font-weight: bold; overflow-wrap: normal; text-align: left; color: rgb(28, 30, 33);"><span class="dgpf1xc5 c77takrd ikxir1m9 it4nsc65 mnmr0lgl b6ewvobd pesago7c fpaaicyn" title="Pexgle">Pexgle的</span></span></a>廣告要求，但可能還有其他此處未列出的影響因素。<div class="dgpf1xc5" accessibilityrole="button"><a target="_blank" href="/help/794535777607370" style="text-decoration-color: var(--fds-black);"><span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; font-weight: bold; overflow-wrap: normal; text-align: left; color: rgb(28, 30, 33);">瞭解詳情</span></a></div></span>`
	},
	PG_WYS_REASON_1_CONTENT: {
		en: 'Pexgle indicated you may have visited www.pexgle.com',
		vi: 'Pexgle đang cố gắng tiếp cận những người có thể đã tương tác với sản phẩm của họ.',
		fr_CA: 'Pexgle a indiqué que vous avez peut-être visité www.pexgle.com.',
		fr: 'Pexgle indique que vous avez peut-être visité www.pexgle.com.',
		pt: 'Pexgle indica que você pode ter visitado www.pexgle.com.',
		nl: 'Pexgle geeft aan dat u www.pexgle.com heeft bezocht.',
		it: 'Pexgle indica che potresti aver visitato www.pexgle.com.',
		ja: 'Pexgleは、www.pexgle.comにアクセスした可能性があることを示します。',
		zh: 'Pexgle表示您可能已經訪問了www.pexgle.com。'
	},
	PG_WYS_REASON_2_CONTENT: {
		en: 'Pexgle is trying to reach people who speak English (UK) and English (US)',
		vi: 'Pexgle đang cố gắng tiếp cận những người nói tiếng Việt',
		fr_CA: 'Pexgle essaie de toucher les personnes qui parlent Anglais (Royaume-Uni) et Anglais (États-Unis).',
		fr: 'Pexgle essaie d&#39;atteindre les personnes qui parlent anglais (Royaume-Uni) et anglais (États-Unis).',
		pt: 'Pexgle está tentando alcançar pessoas que falam inglês (Reino Unido) e inglês (EUA).',
		nl: 'Pexgle probeert mensen te bereiken die Engels (VK) en Engels (VS) spreken.',
		it: 'Pexgle sta cercando di raggiungere persone che parlano inglese (Regno Unito) e inglese (Stati Uniti).',
		ja: 'Pexgleは、英語（英国）および英語（米国）を話す人々にリーチしようとしています。',
		zh: 'Pexgle試圖吸引講英語（英國）和講英語（美國）的人。'
	},
	PG_WYS_REASON_3_CONTENT: {
		en: 'Pexgle is trying to reach people, ages 18 to 54',
		vi: 'Pexgle đang cố gắng tiếp cận những tuổi từ 18 tới 54',
		fr_CA: 'Pexgle essaie de toucher les personnes de 18 à 54 ans.',
		fr: 'Pexgle essaie de toucher des personnes âgées de 18 à 54 ans.',
		pt: 'Pexgle está tentando alcançar pessoas, de 18 a 54 anos.',
		nl: 'Pexgle probeert mensen van 18 tot 54 jaar te bereiken.',
		it: 'Pexgle sta cercando di raggiungere le persone, dai 18 ai 54 anni.',
		ja: 'Pexgleは18〜54歳の人々にアプローチしようとしています。',
		zh: 'Pexgle嘗試接觸18至54歲的人群。'
	},
	PG_WYS_YOU_CAN_DO: {
		en: 'What You Can Do',
		vi: 'Bạn có thể làm gì',
		fr: 'Ce que vous pouvez faire',
		fr_CA: 'Ce que vous pouvez faire',
		pt: 'O que você pode fazer',
		nl: 'Wat je kunt doen',
		it: 'Cosa puoi fare',
		ja: 'オプション',
		zh: '你可以採取的動作'
	},
	PG_WYS_ACTION_1_TITLE: {
		en: 'Hide all ads from this advertiser',
		vi: 'Ẩn tất cả quảng cáo của nhà quảng cáo này',
		fr: 'Masquer toutes les pubs de cette annonceur',
		fr_CA: 'Masquer toutes les pubs de cette annonceur',
		pt: 'Ocultar todos os anúncios desse anunciante',
		nl: 'Alle advertenties van deze adverteerder verbergen',
		it: 'Nascondi tutte le inserzioni di questo inserzionista',
		ja: 'この広告主の広告をすべて非表示にする',
		zh: '隱藏此廣告商的所有廣告'
	},
	PG_WYS_ACTION_1_DES: {
		en: 'You won&#39;t see Pexgle&#39;s ads',
		vi: 'Bạn sẽ không nhìn thấy quảng cáo của Pexgle',
		fr: ' Vous ne verrez pas les pubs de Pexgle',
		fr_CA: 'Vous ne verrez pas les pubs de Pexgle',
		pt: 'Você não verá mais anúncios de de Pexgle',
		nl: 'Je ziet geen advertenties van Pexgle',
		it: 'Non vedrai le inserzioni di Pexgle',
		ja: 'Pexgleの広告は表示されなくなります',
		zh: `<span style="font-family: Arial, sans-serif; font-size: 13px; line-height: 17px; letter-spacing: normal; overflow-wrap: normal; text-align: left; color: rgb(96, 103, 112);">你將不會看到<span class="dgpf1xc5 c77takrd ikxir1m9 it4nsc65 mnmr0lgl b6ewvobd pesago7c" title="GrabFood">Pexgle</span>的廣告。</span>`
	},
	PG_WYS_ACTION_HIDE: {
		en: 'Hide',
		vi: 'Ẩn',
		fr: 'Masquer',
		fr_CA: 'Masquer',
		pt: 'Ocultar',
		nl: 'Verbergen',
		it: 'Nascondi',
		ja: '非表示にする',
		zh: '隱藏'
	},
	PG_WYS_ACTION_2_TITLE: {
		en: 'Make changes to your ad preferences',
		vi: 'Thay đổi tùy chọn quảng cáo',
		fr: 'Modifier vos préférences publicitaires',
		fr_CA: 'Modifier vos préférences publicitaires',
		pt: 'Fazer alterações nas suas preferências de anúncios',
		nl: 'Je advertentievoorkeuren wijzigen',
		it: 'Apporta modifiche alle tue preferenze relative alle inserzioni',
		ja: '広告表示の設定を変更',
		zh: '變更廣告偏好'
	},
	PG_WYS_ACTION_2_DES: {
		en: 'Adjust settings to personalize your ads',
		vi: 'Điều chỉnh cài đặt để cá nhân hóa quảng cáo',
		fr: 'Ajustez les paramètres pour personnaliser vos pubs',
		fr_CA: 'Ajustez les paramètres pour personnaliser vos pubs',
		pt: 'Ajuste as configurações para personalizar seus anúncios',
		nl: 'Pas instellingen aan om je advertenties te personaliseren',
		it: 'Modifica le impostazioni per personalizzare le tue inserzioni',
		ja: '設定を調整して広告をパーソナライズ',
		zh: '調整設定，建立個人化的廣告'
	},
	PG_WYS_IS_GUIDE_HEPL: {
		en: 'Was this explanation useful? ',
		vi: 'Giải thích này có hữu ích không?',
		fr: 'Cette explication vous a-t-elle été utile?',
		fr_CA: 'Cette explication vous a-t-elle été utile?',
		pt: ' Essa explicação foi útil?',
		nl: 'Vond je deze uitleg nuttig?',
		it: 'Ti è stata utile questa spiegazione?',
		ja: 'この説明は役に立ちましたか？',
		zh: '此說明是否有幫助？'
	},
	PG_WYS_YES: {
		en: 'Yes',
		vi: 'Đúng',
		fr: 'Oui',
		fr_CA: 'Oui',
		pt: 'Sim',
		nl: 'Ja',
		it: 'Sì',
		ja: 'はい',
		zh: '是'
	},
	PG_WYS_NO: {
		en: 'No',
		vi: 'Sai',
		fr: 'Non',
		fr_CA: 'Non',
		pt: 'Não',
		nl: ' Nee',
		it: 'No',
		ja: 'いいえ',
		zh: '否'
	},
	PG_UNIT_THOUSAND: {
		en: 'K',
		vi: 'K',
		fr: 'K',
		fr_CA: 'K',
		pt: ' mil',
		nl: ' d.',
		it: '',
		ja: '万',
		zh: '萬'
	},
	PG_UNIT_MILLION: {
		en: 'M',
		vi: ' Triệu',
		fr: 'M',
		fr_CA: 'M',
		pt: ' mi',
		nl: ' mln',
		it: 'mln',
		ja: '',
		zh: ''
	}
};
export { languages };
